[package]
name = "ksh_analyze"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
glsl-lang = { version = "0.7.2", features = ["lexer-v2-full"] }
